#+title: Report Of How This Project Went
- First of all, I can't give myself most of the credit for this, as others did most of the work. I am fine with this, because more to them, but I am also a bit insecure about this. I won't accuse them, and I won't even accuse myself, but man!
  - It'll go away...
- I did start it though. So that's good.
- In retrospect, I might have been better off doing more research on Ontologies. Maybe at least 5, and noting down the common structures of their articles.
- I also mistakenly thought that Fractalism originated from the Muuh, even though it originated from the Perseus Princes first! But exploring how its creators may have derived it from traditional Muuh beliefs could reap insights.
- On some tasks, I definitely demanded too much from myself and reaped too little. Like while fleshing out history, I tried to get myself to brainstorm *20 steps*, instead of the much more reasonable *5 steps*, and the latter task I later did, but only after failing on the former task.
  - I also shouldn't have asked myself to put "EDIT" comments on the history; it isn't an article, and can thus be more loose.
- in terms of Fractalism's principles, I think I might have done well! Grawa came up with them, first, but I think I gave them nice names and all...
- I don't think I should feel too ashamed of merely adding upon other people's work. Technically, everyone is. Newton was "standing on the shoulders of giants".
