#+title: First Draft
* Introduction
Fractalism is an ontology that views all lifeforms around the universe as part of a metaphorical fractal, of which it is the duty of lifeforms to grow in coherence and richness. It emerged in the Perseus Princes, where the Godlings fostered it to unite the then disparate polities, and is what it is most known for. It was derived from Buddhism and Etodism, but also integrated elements from the beliefs of the local sophonts of the Perseus Rift: the hierarchy of Solarism, Metasoft concepts of cosmos and consciousness as networks, and the traditional beliefs of the local Muuh.

Fractalists believe that there are other branes besides ours, and that there are gods in the adjacent branes, similar to the Great Archailects of our own universe. Furthermore, they believe that the fifth dimensional plenum that contains the adjacent branes has an even more powerful being (or set of beings) which hold sway over the affairs of our worlds. Beyond that they believe that there are many higher manifolds, and these plenae hold even greater gods and so on forever, with universes and powers increasing in scale without end.

Similarly Fractalists believe that the archailects are themselves lesser gods, which rule the lesser transapients, while the transapients are above Humans (and the Muuh, the Epp and others), who are set above animals and plants, and these are set above minerals and subatomic particles down to the Planck length.

Fractalism teaches each being to act with compassion and responsibility, guiding lower beings while following the leadership of higher beings. This hierarchical view is similar Solarism but opposes the idea of a single ruling being; the fact that Vatsceh has not prevented other Princes from ascending to eir level is held to be an example of this principle.

Fractalism also has common ground with the prosocial principles of the Communion of Worlds, and the toposophic space exploration of the Technorapture Hypernation.
* Principles
1. Fractalism has three main principles, or the Three Fractals.
Genfractal (The Fractal of Origins): Beings grow in diversity. They should start new forms of life.
2. Gogofractal (The Political Fractal): Beings should act with compassion and responsibility, guiding lower beings while following the leadership of higher beings. They may also temporarily merge with higher beings or form tribeminds to learn wisdom.
   - However, toposophic levels should largely govern themselves, though they may (and should!) ask higher levels for advice.
3. Psychofractal (The Mind/Toposophic Fractal): Beings should explore the range of possible minds.

* History
Fractalism took root in the Perseus Princes. In order to unite the disparate colonies of the Perseus Rift, the alliance of Archai that had formed in the region fostered the development of syncretic philosophies drawing from Etodism, Solarism, Metasoft network philosophy, and Communion mediation practices. The conception of galactic mindkind as a great chain of being, or a Great Fractal, gained popularity as an ontological framework for these beliefs, and in the 70th century Fractalism emerged as a complete ontology. It was widely embraced by modosophonts and apparently also by transapients.
