#+title: History
- some ideas that Nyeti and co have already come up with (especially *in the draft*)
  - Fractalism developed from Etodism and Buddhism
  - Fractalism also took inspiration from Metasoft concepts of consciousness and space as networks
  - Fractalism may or may not have also taken inspiration from Solarism in its hierarichal structure.
- my own ideas of where it came from and how it developed
  - Nayadara (back when she was still an S1) developed Fractalism as an ontology to unite the nearby Perseus Rift empires. To modosophonts it looked like a philosophy of some kind. because technically ontologies are just advanced computerized philosophies lol. She published it on the Known Net for both S0 and S1 to explore.
  - Nayadara may then have ascended to S2, helped by assimilating a few S1 transapients, and then ascended to S3, S4, and then S5.
  - Given Fractalism's encouragement of mergers, this may have helped the Godlings rise. Yeah boi!!!
  - Eguil may also have helped Nayadara in this effort. However, there are many S4 under the S5 that lead their own local regions, of course, so I'll have to take account of that.
  - so how may Fractalism have developed?
  - well, first I'll lay out what it even is
    It is a philosophy that imagines universal society as a fractal of sorts where each sophont has their own place and where toposophic levels extend above the highest archai and below the smallest scales of space. Fractalism's ultimate goal is to keep the "psychofractal" of the universe coherent and grow it in richness.

    It has three principles - or ternions:
    - Genfractal: Beings start out from  simple origins but gradually grow in complexity and diversity.
    - Gogofractal: Beings rule in diverse ways.
    - Psychofractal: The ultimate entity in Fractalism. Beings rule over those of a lower toposophic fractal, but for spiritual guidance one may temporarily merge with a being of a higher toposophic level...

    I can see how it might be related to Buddhism and Etodism now!
  - Of course, it may simply have looked the same to modosophonts since its inception.
  - The local Governer Transapients and Archai used Fractalism to unite themselves. It's not clear how lol.
- another attempt at making a history lol
  - actually, we already came up with one, but we need to expand it (mostly because it is ridiculous to readers that there is only one paragraph on the history)
    - so here it is: the Perseus Princes lacked a defining ideology, but the local alliance of Godlings fostered the development of Fractalism to unite them. since they were Metasoft, Solarists, and such, Fractalism incorporated elements of all of those so that Metasoft people and Solarists could be united! many modosophonts and a surprising many transapients embraced it
  - I'll expand on each of the events then
  - expansion of "the local alliance of Godlings fostered the development of Fractalism to unite them"
    - The Princes began their quest by sponsoring Fractalism, I Guess. They asked transapients to embrace it, who them asked modosophonts to embraced it, and ya da ya da
    - maybe it was published on the Known Net. I definitely should use the history I came up with above.
  - expansion of "modosophonts and transapients embraced it"
    - maybe just list the colonies that embraced it?
    - "The core systems of the Perseus Princes were the first to embrace it"
      - but why? does distance matter as much? it certainly would to some extent because of light lag, but did the Princes have comm gauge wormholes by this point?
      - Pluton, and such could be the first to embrace it
        - man we need to flesh out the other Princes and their capitals
    - "It spread rapidly like a meme through virches"
    - effects on culture?
      - historical Fractalist artworks?
        - The Berva Set.
          - maybe Berva was a philosopher before becoming a prince? or is still a philosopher?
        - Bliffoth's Abstract Linkers
        - Busard's Swarms
  - what else to expand upon? time is running out
  - maybe expand on what the uniting looked like?
    - "Metasoft and Solarists both found it appealing, as it was compatible with and complemented their deeply held beliefs. And at last, they could see that they had a lot in common with each other."
      - beautiful! 🥹
