#+title: Origins For Fractalism
- Perhaps Fractalism was a Muuh artistic movement around Fractals that started when one scholar discovered them. Then it somehow grew into a spiritual and societal framework?
- While writing the data panels for the Perseus Princes, we have generally assumed that Fractalism is an *ontology*. So perhaps the S1s in the Perseus region made Fractalism as a way to unite modos, and even the higher empires?
- I am wondering what would be unique about Fractalism. It has the three fractals for sure. We need to come up with ideas.
- Fractalism is a developed form of Buddhism though (the article mentions that) so it didn't originate from the Muuh. It definitely originated in the region.
- Perhaps Fractalism was inspired by the proto-Fractalist beliefs of the Muuh colonies in the region?
- If Fractalism is a developed form of Buddhism, and Buddhism is about finding bad thought patterns and destroying them and finding good thought patterns and enhancing them, then what would Fractalism be about based on this?
  - Just to refresh, let me remind myself of three Ternions of Fractalism here
    - Genfractal: the fractal of origins.
    - Noofractal: the fractal of minds and toposophic levels
    - Gogofractal: the fractal of governance
- Fractal Cosmology may have inspired Fractalism.
- Fractals are self-repeating patterns. So how would that affect Fractalism?
  - let's flesh out the three ternions a bit more
  - Genfractal
    - here, the three origins branch out and endlessly extend. but this is about self-repeating patterns, so what about the progenitors would repeat themselves in their descendants?
  - Noofractal:
    - here, the self-repeating patterns may be in minds sharing common characteristics with both lower and upper minds, and things being "nested"
  - Gogofractal:
    - perhaps the same governance structure is used over and over again on different scales? no, that's impossible.
- Etodism may also have inspired Fractalism.
- Oh oh! perhaps orthogonality and reuse is a part of Fractalism. I just felt like that might be a useful idea?
